### ISSUE TITLE
Incorrect variable on 'bounce' response function causing error

### ISSUE THREAD

**Issue by xenthral** [kikito/bump.lua#12]
line 299: "local tch, move = col.tch, col.move"
should be col.touch

Loving the lib so far, hope you keep expanding on it. I'm considering forking it and adding a stateful rewind in the future for networking.

Just so I dont make a separate ticket:
Have you considered adding a function to mirror world:check functionality, but with the express purpose of testing a change in shape boundaries?
The only current way I believe is to use world:update but that doesnt generate collision info, forcing the necessity to actually take a delta of the current rect state, the next rect state, and simulate the motion in those directions - quite clunky!

**Comment by kikito** [comment]
Hey, thanks for the issue report - I have released a fix.

> Have you considered adding a function to mirror world:check functionality, but with the express purpose of testing a change in shape boundaries?

I am sorry but I don't know what "testing a change in shape boundaries" means in that phrase. What is a "shape" in and what is a "change"?

> The only current way I believe is to use world:update but that doesnt generate collision info, forcing the necessity to actually take a delta of the current rect state, the next rect state, and simulate the motion in those directions - quite clunky!

Not sure I understand you correctly, but it seems that world:project might be what you are looking for.

**Comment by xenthral** [comment]
>I am sorry but I don't know what "testing a change in shape boundaries" means in that phrase. What is a "shape" in and what is a "change"?

A character is crouching, his rectangle shape is 20x20, he stands up, now his rectangle shape is 20x40.
If I want to ensure he does not clip into the wall geometry I have to test a motion - with either world:project or world:check or world:move, of 20 units upwards.
This is not intuitive since you want to just use world:update to change the rectangle shape/size, rather than create motion.

**Comment by kikito** [comment]
I understand now.

What you want to do can't be done in bump. In this library, boxes "stay the same size while they move or collide". Supporting "collisions while a box changes size" would make the code larger and slower, and would complicate the interface too.

In other words: You can move/collide an item and then change its size. Or you can change the size and then move/collide it. You can't do both simultaneously. This is on purpose.

> A character is crouching, his rectangle shape is 20x20, he stands up, now his rectangle shape is 20x40.

For that particular case I see two options:

If your character only has two states (standing up and crouching) I would not test a "motion"; I would check that he fits standing up. You can do that with world:queryRect. If there is a ceiling in the space the "standing" player would occupy, then it can't stand up, and must remain crouched.

For a more advanced case where the player to "gradually increases its height to the maximum available ceiling height" I would also use world:queryRect with the max height of the player. Instead of checking if there is one ceiling, I would get all the ceilings on that rect and pick the lowest one. That would be the max height for the player.

**Comment by xenthral** [comment]
>Supporting "collisions while a box changes size" would make the code larger and slower, and would complicate the interface too.
I see, though what I was proposing was more of a new test query, rather than full fledged change shape+motion support, but I can understand if that would be unwieldly in any case.

>You can do that with world:queryRect. If there is a ceiling in the space the "standing" player would occupy
Yes thats the approach I'm using at this point, the problem is that queryRect does not generate collision data, so if I set up logic to deal with the consequences of regular motion, it has to be replicated going through the results of queryRect.

Though it occurs to me now that I could just use queryRect and then do a world:move() in the same place to get that collision set, so I'll probably do that from now on. Thanks a ton.

**Comment by kikito** [comment]
No problemo, thanks for using my lib. Good luck with the game! :)
