### ISSUE TITLE
not an issue, just a little suggetion

### ISSUE THREAD

**Issue by alexzheng** [kikito/bump.lua#16]
getDictItemsInCellRect return an array and use for i = 1, #items maybe a little more efficient since pairs is   slow.

**Comment by kikito** [comment]
Hi there,

I understand why you think that way. If you look at how the result of `getDictItemsInCellRect` is used, it seems indeed less efficient: in the code, it is used only for iterating over it with `pairs`.

The problem however is not in how this table is *used*, but in how it's *built*.

You probably know that bump divides the space into a "grid". Each cell of the grid has "a list of items which touch the grid". You can see that grid when you activate the "debug mode" (tab key) in both the simpledemo and the demo.

If an item is big enough, or is in the right coordinates, it can be in several grid cells at the same time. This happens often with moving items.

What `getDictItemsInCellRect` does is, given a rectangle of cells, obtain the list of items touching any of the cells in that rectangle. But I don't want duplicates in that list (That could mean duplicated collisions). I can't simply "go over each cell and include each item in that cell in an array and return that".

That's why I organize the resulting table as a dictionary, where the items are the "keys". That way, even if I find the same item in lots of cells, I only write it in the table once. I don't risk having duplicates: the following table has just one instance of the string `'potato``, even if "assigned 100 times":

``` lua
local dict = {}
for i=1,100 do
  dict['potato'] = true
end
```

So using a dictionary like this gets rid of the duplicates. Now, why don't I just build an array from that dictionary?. Well, I could, but in order to do that, I still would have to use `pairs`:

``` lua
local array, len = {}, 0
for k,_ in pairs(dict) do
  len = len + 1
  array[len] = k
end
```

So that is your reason. I must build a dictionary in order to discard duplicates quickly. And once I have a dictionary, it is better to use that dictionary directly instead of transforming it into an array: `pairs` is  slower than a `for i=1,#len` loop, yes. But `pairs` is faster than `pairs` *+* `for i=1,#len`.

I hope this answers your question. Thanks anyway for taking the time to make this suggestion! I will close this issue now, but feel free to comment/reopen if you need more feedback.

**Comment by alexzheng** [comment]
Hi,thanks for you detailed reply.
It's a great lib,I intend to build an platform game using it.
I did not mean simply add all items to an array, using another table to check if the item is already added,
however, after I tested the performance as following,outputs:
0.48664599657059
0.49274200201035

 the difference could be ignored.

local array = {}
local tags = {}

local keys = {}

local items = {}

local counts = 1000000

for i = 1, counts do
	items[i] = {i}
end

local time = os.timer()

local len = 0
for i = 1, counts do
	if not tags[items[i]] then
		len = len + 1
		array[len] = items[i]
		tags[items[i]] = true
	end
end

for i = 1, counts do
	array[i] = nil
end



print(os.timer() - time)

time = os.timer()

for i = 1, counts do
	keys[items[i]] = true
end

for k, _ in pairs(keys) do
	keys[k] = nil
end

print(os.timer() - time)
