### ISSUE TITLE
Possible to set default filter?

### ISSUE THREAD

**Issue by noc7c9** [kikito/bump.lua#21]
As the title says, For example say I'd like to set the default filter to `cross` for all collisions. Just as a convenience really.

**Comment by Kingdaro** [comment]
+1. It'd probably be a good idea to add an API function for this, though you can change the source code for your project specifically if you want:
```lua
local defaultFilter = function()
  return 'cross'
end
```

**Comment by kikito** [comment]
Hi there!

Instead of relying on a global variable to change this, I would set it up in the world. Right now you can achieve this by redefining the `move` function as follows, on each world you create:

``` lua
local world = bump.newWorld(50)

local oldMove = world.move
world.move = function(self, item, goalX, goalY, filter)
  return oldMove(self, item, goalX, goalY, filter or bump.responses.cross)
end
```

I guess I could add a second optional variable to `bump.newWorld` to set this up, but I am not sure it is worth it - it seems that most people are ok with slide being the default.

@noc7c9, is this method enough for you?

**Comment by noc7c9** [comment]
I ended up doing something which basically amounts to redefining move as @kikito suggested.

Honestly this was more of "can I do this?", rather than a "I need a solution" kind of issue anyway which occurred to me while prototyping.

Anyway thanks for the responses and the great lib. :)

**Comment by kikito** [comment]
:+1:
