### ISSUE TITLE
Images and collisions

### ISSUE THREAD

**Issue by voronianski** [kikito/bump.lua#31]
Hey, this issue is more about some piece of advice rather than bug report.

I'm using bump inside my game to detect collisions between player, bullets and enemies. All entities are images and are drawn this way:

```lua
-- player for example
function Player:draw ()
  love.graphics.draw(playerImage, self.x, self.y, self.rotation, playerScale, playerScale, self.width / 2, self.height / 2)
end
```

This allows to create a proper rotation effect. However there is a problem with collisions: 

<img width="500" src="https://cloud.githubusercontent.com/assets/974035/21679858/82006660-d346-11e6-8ec3-32106da6caea.gif">

<img width="500" alt="screen shot 2017-01-05 at 12 56 11 pm" src="https://cloud.githubusercontent.com/assets/974035/21679857/7d0809ce-d346-11e6-933b-e10c10f8ea05.png">

The origin of the image is in center but as I understand bump assumes that it's left and top coords and makes image bounds this way.

**Comment by kikito** [comment]
Hi, there. Thanks for using bump!

bump doesn't know anything about representation. It doesn't "assume" anything either - it can't. Bump can be used in other game engines besides LÖVE, where the y component goes up. It makes no difference to it. How you draw things (or whether you draw them or not) is entirely up to you.

The way I see it, either you are drawing the rectangles of your second image the wrong way (the collisions would not match the rectangles), or you are drawing the images the wrong way (the collisions would match the rectangles). The error must be somewhere else in your code. Without seeing it it's difficult to tell.

**Comment by voronianski** [comment]
@kikito hi, thanks for the answer, problem was in drawing, `x` and `y` needed to be center coordinates:

```lua
function Player:draw ()
  local center = self:getCenter()
  love.graphics.draw(playerImage, center.x, self.y, center.rotation, playerScale, playerScale, self.width / 2, self.height / 2)
end
```

**Comment by kikito** [comment]
I'm glad you found the error. Relevant link: [First Rule of Programming](https://blog.codinghorror.com/the-first-rule-of-programming-its-always-your-fault/) :)

That said, it is a bit strange that you had to solve it that way. It seems to me that there is some kind of "misalignment" between the data you use on your "Player" and the data you pass to bump. Don't be surprised if you have to modify that draw function again in the future :)

Good luck and thanks again for using bump!

**Comment by voronianski** [comment]
@kikito thanks, as we started a discussion here maybe you could advice some solution for enemy entities steering behavior?

**Comment by kikito** [comment]
Well that depends on the kind of game you are trying to make.

If you are doing a straight up shoot-them up then you don't need to make
your enemy ships very intelligent - just add lots of them. You can ignore
physics here, and concentrate on making the enemies look interesting. It
would be fine to make them go along predefined (or semi-randomized) paths
relative to the player -  https://www.youtube.com/watch?v=Z3xBIBSNkk0

If you are trying to be more "simulationist", you will start getting into
trouble. Space is somewhat unintuitive with regards of momentum, gravity
etc. If your ship moves like the ship in Asteroids, then so should the
enemies. And it turns out that moving this way is kind of complex, even if
it's just in 2d. It's called "motion planning", and it is a field on itself.

If you are not super strong in math and physics, I would recommend staying
with the arcade-y approach. I tried to do a physics-based top down shooter
once and I ended up giving up (I am not a math or physics expert).
Nevertheless, here are a couple StackOverflow questions I did while
investigating, in case they help you:

* Orientating a turret-like object using torques:
http://stackoverflow.com/questions/2617476/physics-game-programming-box2d-orientating-a-turret-like-object-using-torques
* 2-d trajectory planning of a spaceship with physics:
http://stackoverflow.com/questions/2560817/2d-trajectory-planning-of-a-spaceship-with-physics

On Fri, Jan 6, 2017 at 6:04 PM, Dmitri Voronianski <notifications@github.com

**Comment by voronianski** [comment]
@kikito thanks a lot! I'm not physics and math expert as well but my first idea was to make enemies that will try to follow player. I assume that this will make game harder and more interesting, however random movement could be an option too.

**Comment by voronianski** [comment]
@kikito I've found this example https://github.com/agilul/spaceshooter-love2d kind of similar to what I want achieve, maybe this example will be interesting for you as well.

**Comment by voronianski** [comment]
@kikito thanks again, your questions on stackoverflow helped me a lot. I managed to recreate basic seeking behavior for enemy spaceships. However there's still problem with rotation, I have created stackoverflow question as well - http://stackoverflow.com/questions/41521058/get-angle-rotation-for-entity-for-steering-seeking-behavior-in-2d-game.
