### ISSUE TITLE
Can't query my object.

### ISSUE THREAD

**Issue by stzengh** [kikito/bump.lua#36]
Hi 

Here is my test code:

local world = bump.newWorld(64)
local A = {name="A"}

-- insert both rectangles into bump
world:add(A,   0, 0, 10, 10) -- x,y, width, height

local items, len = world:querySegment(
	-1000, -1000,
	1000, 1200,
	nil
)

print(len)   -- len is zero    
 
Is bug?

**Comment by kikito** [comment]
Have you tried drawing the object and segment? Are you sure they must
intersect?

On May 15, 2017 14:36, "stzengh" <notifications@github.com> wrote:

Hi

Here is my test code:

local world = bump.newWorld(64)
local A = {name="A"}

-- insert both rectangles into bump
world:add(A, 0, 0, 10, 10) -- x,y, width, height

local items, len = world:querySegment(
-1000, -1000,
1000, 1200,
nil
)

print(len) -- len is zero

Is bug?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kikito/bump.lua/issues/36>, or mute the thread

**Comment by stzengh** [comment]
From the coordinate  the A object is in the query rect.

**Comment by kikito** [comment]
I'm sorry, but I think you are wrong. Try drawing the rectangle (0,0,10,10) and the segment (-1000,-1000,1000,12000). They don't intersect, by a significant margin.
