### ISSUE TITLE
Moving mechanics

### ISSUE THREAD

**Issue by implicit-invocation** [kikito/bump.lua#49]
I want to implement a topdown game with moving mechanics that can push player from any direction (and kill player if pushed into walls).  
How can I achieve that with bump?

**Comment by alexmozaidze** [comment]
I don't think that's a good question. Nobody wants to design a game for you, besides, everything is fully documented in README, and you should remember that bump is simply a collision detection library, and you're the one doing all the movement logic, though, bump has some collision *response* capabilities built-in (more on that in a minute).

If you wanna learn how to write games, you should probably learn how to do simple math with vectors. I highly recommend Freya Holmer's [Math for Game Devs [Part 1]](https://youtu.be/MOYiVLEnhrw?si=iQEt-VRn_4hS8_Ys), it teaches the most basic stuff you need for game development.

### And to answer your question

You can use `world:move` to tell bump where you want your player to go, and it will calculate the actual position depending on wether it collided with anything or not. (see [`world:move`](https://github.com/kikito/bump.lua#moving-an-item-in-the-world-with-collision-resolution))

To control what should happen on each collision, you pass a `<filter>` to `world:move`, which is basically a function that determines how bump should respond to the collision. If you want to kill the player off whenever he touches a wall, you most likely want to have a `<filter>` like this:
```lua
function playerFilter(player, other)
   if other.isWall() then
      killPlayer()
   end

   -- Rest of the logic ...
end
```

In order to push a player, well... You learn how to do game dev math. It's really simple once you wrap your head around vectors.

If you have any questions that are as broad, you should probably ask them in Love2D's Discord server or on the IRC channel, which are linked on [love2d.org](https://love2d.org/)

<details>
<summary></summary>
And yes, I know I'm 5 years late with the response.
</details>

**Comment by implicit-invocation** [comment]
Wow, such a late and unhelpful response.  

Your answer is “use math”? Okay, linear algebra requires for any game with graphics. But for unrealistic physics for 2D game and for them to feel good, you need “tricks”.   

My own answer for this question is the approach from celeste’s dev. Moving everything that need to move pixel by pixel, you should save yourself a lot of headaches and handle the collision resolve much more easily. I built a platformer engine on that approach (typescript) and (maybe) I will release it when I have time.

**Comment by alexmozaidze** [comment]
I don't think Celeste is a "top-down" game, I think of an RPG when I hear "top-down game". Of course it's the subtle things that make a platformer nice to control (I am making a platformer too), but I don't think that was even the question you originally asked.

Vector math is always a nice skill to have when making any game, I just wanted to share some knowledge, no more, no less.

**Comment by implicit-invocation** [comment]
I use that for my top-down control too, just turn off gravity and disable all ground check.

**Comment by sieben07** [comment]
Just out of curiosity, are there any links to the "tricks", or the approach from the celest devs?

**Comment by alexmozaidze** [comment]
@sieben07 
Platformer tricks: https://maddymakesgames.com/articles/celeste_and_forgiveness/index.html
Physics stuff: https://maddymakesgames.com/articles/celeste_and_towerfall_physics/index.html
